// <auto-generated />
using System;
using ContactsApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactsApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210930020859_SetupContact")]
    partial class SetupContact
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactsApi.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31b9ba25-d213-44b5-a0ea-1dc7d9ca6300"),
                            Company = "DevWorking",
                            Email = "nalvarez23@live.com.ar",
                            FirstName = "Nahuel",
                            LastName = "Alvarez",
                            PhoneNumber = "+543794637353"
                        },
                        new
                        {
                            Id = new Guid("fb832f2f-d6a3-4fae-a190-7a41879d0a0e"),
                            Company = "Development",
                            Email = "test@gmail.com",
                            FirstName = "Test",
                            LastName = "Test",
                            PhoneNumber = "+111111111111"
                        },
                        new
                        {
                            Id = new Guid("f4f4f178-7ba2-450a-86f5-3e902ae3bc93"),
                            Company = "Development2",
                            Email = "anothertest@gmail.com",
                            FirstName = "Test2",
                            LastName = "Test2",
                            PhoneNumber = "+12211111111111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
